"""
Strategy schema — defines what a strategy looks like and validates it.
Strategies are YAML files generated by the AI during discussion with user.
"""

import yaml
import os
import uuid
from datetime import datetime
from pathlib import Path


STRATEGIES_DIR = os.path.expanduser("~/.dhan-mcp/strategies")


EXAMPLE_STRATEGY = """
id: rsi_ema_nifty_v1
name: "RSI + EMA Crossover on NIFTY"
version: 1
created_at: "2026-04-05"

# What to trade
instrument:
  index: NIFTY
  option_preference: ATM       # ATM, ITM, OTM, or specific offset like ATM+100
  option_type: CE              # CE, PE, or BOTH
  trade_type: BUY              # BUY, SELL, or BOTH
  expiry_preference: nearest   # nearest, next_week, monthly

# Monitoring
interval: 5                    # minutes between each check
data_lookback: 30              # days of daily data to preload

# Indicators needed (framework computes these automatically)
indicators:
  - name: ema_fast
    type: EMA
    period: 9
    source: close
  - name: ema_slow
    type: EMA
    period: 21
    source: close
  - name: rsi
    type: RSI
    period: 14
    source: close
  - name: vwap
    type: VWAP

# Entry rules (ALL must be true to enter)
entry:
  conditions:
    - "rsi < 30"
    - "ema_fast > ema_slow"
    - "close > vwap"
  lots: 1

# Exit rules (ANY triggers exit)
# Use 'conditions' for single-direction, or 'conditions_ce'/'conditions_pe' for dual-direction
exit:
  conditions:
    - "rsi > 70"
    - "ema_fast < ema_slow"
  max_bars: 6            # optional: time stop after N candles

# Stop loss (types: percentage, points, atr, trailing)
stop_loss:
  type: atr              # atr: dynamic based on ATR indicator
  multiplier: 2.0        # SL = ATR × multiplier
  atr_indicator: atr     # name of ATR indicator in your indicators list
  min: 50                # optional: minimum SL in points
  max: 120               # optional: maximum SL in points
  # For trailing: {type: trailing, value: 40, trail_type: points, activate_after: 80}

# Target
target:
  type: percentage
  value: 40            # 40% above entry price

# Risk limits
risk:
  max_loss_per_day: 5000       # INR, stop trading if hit
  max_trades_per_day: 5
  cool_off_after_loss: 2       # skip N signals after a losing trade
"""


REQUIRED_FIELDS = [
    "id", "name", "instrument", "interval", "indicators",
    "entry", "exit", "stop_loss", "target", "risk",
]


def validate_strategy(strategy: dict) -> dict:
    """Validate a strategy dict. Returns {valid: bool, errors: list}."""
    errors = []

    for field in REQUIRED_FIELDS:
        if field not in strategy:
            errors.append(f"Missing required field: {field}")

    inst = strategy.get("instrument", {})
    if inst.get("index") not in ("NIFTY", "BANKNIFTY"):
        errors.append("instrument.index must be NIFTY or BANKNIFTY")
    if inst.get("option_preference") not in ("ATM", "ITM", "OTM") and not str(inst.get("option_preference", "")).startswith("ATM"):
        errors.append("instrument.option_preference must be ATM, ITM, OTM, or ATM+/-offset")
    if inst.get("trade_type") not in ("BUY", "SELL", "BOTH"):
        errors.append("instrument.trade_type must be BUY, SELL, or BOTH")

    indicators = strategy.get("indicators", [])
    if not indicators:
        errors.append("At least one indicator is required")
    for ind in indicators:
        if "name" not in ind or "type" not in ind:
            errors.append(f"Indicator missing name or type: {ind}")

    entry = strategy.get("entry", {})
    has_single = bool(entry.get("conditions"))
    has_dual = bool(entry.get("conditions_ce")) and bool(entry.get("conditions_pe"))
    if not has_single and not has_dual:
        errors.append("entry must have 'conditions' OR both 'conditions_ce' and 'conditions_pe'")

    exit_rules = strategy.get("exit", {})
    has_single_exit = bool(exit_rules.get("conditions"))
    has_dual_exit = bool(exit_rules.get("conditions_ce")) and bool(exit_rules.get("conditions_pe"))
    if not has_single_exit and not has_dual_exit:
        errors.append("exit must have 'conditions' OR both 'conditions_ce' and 'conditions_pe'")

    sl = strategy.get("stop_loss", {})
    if sl.get("type") not in ("percentage", "points", "trailing", "atr"):
        errors.append("stop_loss.type must be percentage, points, trailing, or atr")

    target = strategy.get("target", {})
    if target.get("type") not in ("percentage", "points"):
        errors.append("target.type must be percentage or points")

    return {"valid": len(errors) == 0, "errors": errors}


def save_strategy(strategy: dict) -> str:
    """Save strategy YAML to disk. Returns file path."""
    Path(STRATEGIES_DIR).mkdir(parents=True, exist_ok=True)

    if "id" not in strategy:
        strategy["id"] = f"strategy_{uuid.uuid4().hex[:8]}"
    if "created_at" not in strategy:
        strategy["created_at"] = datetime.now().isoformat()

    path = os.path.join(STRATEGIES_DIR, f"{strategy['id']}.yaml")
    with open(path, "w") as f:
        yaml.dump(strategy, f, default_flow_style=False, sort_keys=False)
    return path


def load_strategy(strategy_id: str) -> dict:
    """Load a strategy from disk."""
    path = os.path.join(STRATEGIES_DIR, f"{strategy_id}.yaml")
    if not os.path.exists(path):
        return None
    with open(path, "r") as f:
        return yaml.safe_load(f)


def list_strategies() -> list:
    """List all saved strategies."""
    Path(STRATEGIES_DIR).mkdir(parents=True, exist_ok=True)
    strategies = []
    for f in os.listdir(STRATEGIES_DIR):
        if f.endswith(".yaml"):
            path = os.path.join(STRATEGIES_DIR, f)
            with open(path, "r") as fh:
                s = yaml.safe_load(fh)
                strategies.append({
                    "id": s.get("id"),
                    "name": s.get("name"),
                    "version": s.get("version"),
                    "index": s.get("instrument", {}).get("index"),
                    "interval": s.get("interval"),
                    "created_at": s.get("created_at"),
                })
    return strategies
